server:
  port: 9000
spring:
  application:
    name: votacao-api
  datasource:
    url: jdbc:mysql://localhost:3306/db-coop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id
session:
  duration: 60
topic:
  name:
    producer: resultado_votacao
auto:
  create:
    topics:
      enable: true